---
abstract: 'Very simple YouTube video download interface'
author:
  - 'xaicron E<lt>xaicron {@} cpan.orgE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-YouTube-Download
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  WWW::YouTube::Download:
    file: lib/WWW/YouTube/Download.pm
    version: 0.46
requires:
  HTML::Entities: 0
  JSON: 0
  LWP::UserAgent: 0
  Term::ANSIColor: 0
  URI: 0
  URI::QueryParam: 0
  XML::TreePP: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.46
