---
abstract: 'Very simple YouTube video download interface'
author:
  - 'xaicron <xaicron {@} cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.53, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: www-youtube-download
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  WWW::YouTube::Download:
    file: lib/WWW/YouTube/Download.pm
    version: 0.48
requires:
  HTML::Entities: 0
  JSON: 0
  LWP::UserAgent: 0
  Term::ANSIColor: 0
  URI: 0
  URI::QueryParam: 0
  XML::TreePP: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/xaicron/p5-www-youtube-download/issues
  homepage: https://github.com/xaicron/p5-www-youtube-download
  repository: git://github.com/xaicron/p5-www-youtube-download
version: 0.48
x_contributors:
  - 'akiym <akiyama@8ant.org>'
  - 'Maurice <mauricemengel@gmail.com>'
  - 'ks <ks-for-git@live.jp>'
  - 'isync <o.zucker@web.de>'
  - 'Yusuke Wada <yusuke@kamawada.com>'
  - 'Flavio Poletti <flavio@polettix.it>'
  - 'xaicron <xaicron@gmail.com>'
