---
abstract: 'Very simply YouTube video download interface.'
author:
  - 'Yuji Shimada'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-YouTube-Download
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::Entities: 0
  JSON: 0
  LWP::UserAgent: 0
  URI: 0
  URI::QueryParam: 0
  XML::TreePP: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/xaicron/p5-www-youtube-download
version: 0.37
